name: Build and Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build-macos:
    name: Build on macOS
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install Python dependencies (split)
        working-directory: GUI/PyQt
        run: |
          python -m pip install --upgrade pip
          pip install --no-cache-dir PySide6==6.9.2 pyinstaller==6.15
          pip install --no-cache-dir numpy==2.3.2 scipy==1.16.1 pandas==2.3.2 pyqtgraph==0.13.7 pyserial==3.5

      - name: Debug macOS specifics
        run: |
          echo "=== PySide6 plugin path ==="
          python -c "from PySide6 import QtCore; print(QtCore.QLibraryInfo.location(QtCore.QLibraryInfo.PluginsPath))"

          echo "=== Contents of GUI/PyQt ==="
          ls -lah GUI/PyQt

          echo "=== .icns file info ==="
          ls -lh GUI/PyQt/Spikeling.icns || true

      - name: Select .spec file
        run: |
          echo "SPEC_FILE=Spikeling-mac.spec" >> $GITHUB_ENV
          echo "OS_NAME=macOS" >> $GITHUB_ENV

      - name: Build with PyInstaller
        working-directory: GUI/PyQt
        run: |
          echo "Using spec file: $SPEC_FILE"
          pyinstaller --clean --log-level=DEBUG "$SPEC_FILE"

      - name: Verify macOS executable
        run: |
          chmod +x GUI/PyQt/dist/Spikeling
          echo "Executable info:"
          ls -lh GUI/PyQt/dist/Spikeling
          GUI/PyQt/dist/Spikeling --help || echo "Help check skipped"

      - name: Package build with additional folders
        run: |
          VERSION=${GITHUB_REF_NAME}
          ZIP_NAME=Spikeling-${VERSION}-${OS_NAME}.zip

          mkdir -p Spikeling

          # Copy executable
          cp GUI/PyQt/dist/Spikeling Spikeling/
          chmod +x Spikeling/Spikeling

          # Copy extra folders if they exist
          for dir in Recordings Neurons Stimuli; do
            if [ -d "GUI/PyQt/$dir" ]; then
              cp -r "GUI/PyQt/$dir" Spikeling/
            else
              echo "Skipping missing folder: $dir"
            fi
          done

          # Ensure OS-specific folder exists
          mkdir -p GUI/${OS_NAME}

          # Remove any old zip with same name
          rm -f GUI/${OS_NAME}/${ZIP_NAME}

          # Create zip directly inside GUI/${OS_NAME}
          (cd Spikeling && zip -r ../GUI/${OS_NAME}/${ZIP_NAME} .)

      - name: Cleanup intermediate folders
        run: |
          rm -rf GUI/PyQt/build GUI/PyQt/dist GUI/PyQt/__pycache__ Spikeling

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: Spikeling-macos
          path: GUI/${{ env.OS_NAME }}/*.zip
