name: Build and Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build-macos:
    name: Build on macOS
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install Python dependencies (split)
        working-directory: GUI/PyQt
        run: |
          python -m pip install --upgrade pip
          pip install --no-cache-dir PySide6==6.9.2 pyinstaller==6.15
          pip install --no-cache-dir numpy==2.3.2 scipy==1.16.1 pandas==2.3.2 pyqtgraph==0.13.7 pyserial==3.5

      - name: Debug macOS specifics
        run: |
          echo "=== PySide6 plugin path ==="
          python -c "from PySide6 import QtCore; print(QtCore.QLibraryInfo.location(QtCore.QLibraryInfo.PluginsPath))"

          echo "=== Contents of GUI/PyQt ==="
          ls -lah GUI/PyQt

          echo "=== .icns file info ==="
          ls -lh GUI/PyQt/Spikeling.icns

      - name: Select .spec file
        run: |
          echo "SPEC_FILE=Spikeling-mac.spec" >> $GITHUB_ENV
          echo "OS_NAME=macOS" >> $GITHUB_ENV

      - name: Build with PyInstaller
        working-directory: GUI/PyQt
        run: |
          echo "Using spec file: $SPEC_FILE"
          pyinstaller --clean --log-level=DEBUG "$SPEC_FILE"

      - name: Verify macOS executable
        run: |
          chmod +x GUI/PyQt/dist/Spikeling
          echo "Executable info:"
          ls -lh GUI/PyQt/dist/Spikeling
          # Run version/help safely
          GUI/PyQt/dist/Spikeling --help || echo "Help check skipped"

      - name: Package build with additional folders
        run: |
          VERSION=${GITHUB_REF_NAME}
          ZIP_NAME=Spikeling-${VERSION}-${OS_NAME}.zip

          mkdir -p release

          # Copy executable
          cp GUI/PyQt/dist/Spikeling release/
          chmod +x release/Spikeling

          # Copy extra folders
          cp -r GUI/PyQt/Recordings release/
          cp -r GUI/PyQt/Neuron release/
          cp -r GUI/PyQt/Stimuli release/

          # Create OS-specific folder and remove old zip if exists
          mkdir -p GUI/${OS_NAME}
          rm -f GUI/${OS_NAME}/${ZIP_NAME}

          # Create zip
          zip -r "$ZIP_NAME" release/*

          # Move zip into GUI/<OS> folder
          mv "$ZIP_NAME" GUI/${OS_NAME}/

      - name: Cleanup intermediate folders
        run: |
          rm -rf GUI/PyQt/build GUI/PyQt/dist GUI/PyQt/__pycache__ release

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: Spikeling-macos
          path: GUI/${{ env.OS_NAME }}/*.zip
