# on:
#   push:
#     tags:
#       - 'v*'
#
# jobs:
#   pyinstaller-build:
#     runs-on: [ubuntu-20.04]
#     steps:
#
#       - name: Install dependencies
#         run: |
#           python -m pip install --upgrade pip
#           pip install -r requirements.txt
#
#       - name: Create Executable
#         uses: sayyid5416/pyinstaller@v1
#         with:
#           python_ver: '3.7'
#           spec: 'GUI\PyQt\Main.spec'
#           requirements: 'GUI\PyQt\requirements.txt'
#           upload_exe_with_name: 'Spikeling'
#           options:  --onefile
