name: Build All Platforms

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.7'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Create Executable
        uses: sayyid5416/pyinstaller@v1
        with:
          python_ver: '3.7'
          spec: 'GUI\PyQt\Main.spec'
          requirements: 'GUI\PyQt\requirements.txt'
          upload_exe_with_name: 'Spikeling'
          options:  --onefile

      - name: Upload Release Asset
        uses: softprops/action-gh-release@v2
        with:
          files: dist/MyApp.exe  # or .dmg or .AppImage
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
