on:
  push:
    tags:
      - 'v*'

jobs:
  pyinstaller-build:
    runs-on: [ubuntu-20.04]
    steps:
      - name: Create Executable
        uses: sayyid5416/pyinstaller@v1
        with:
          python_ver: '3.8'
          requirements: 'GUI/PyQt/requirements.txt'
          #upload_exe_with_name: 'Spikeling'
          options:  -F, # -n Spikeling   #, -i GUI/PyQt/Spikeling.ico
          spec: 'GUI/PyQt/Main.py'
          exe_path: "./dist"
          upload_exe_with_name: "Spikeling"