on:
  push:
    tags:
      - 'v*'

jobs:
  pyinstaller-build:
    runs-on: [windows-latest]
    steps:
      - name: Create Executable
        uses: sayyid5416/pyinstaller@v1
        with:
          python_ver: '3.8'
          spec: 'GUI/PyQt/Main.py'
          requirements: 'GUI/PyQt/requirements.txt'
          upload_exe_with_name: 'Spikeling'
          options: -w -n Spikeling -i GUI/PyQt/Spikeling.ico
          exe_path: "./dist"
          upload_exe_with_name: "Spikeling.exe"